<a href="https://colab.research.google.com/github/szh141/colab/blob/main/Advanced_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://blog.stackademic.com/numpy-magic-advanced-techniques-and-best-practices-46344dd37031

In [2]:
#stacking np.array
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

arr_stacked = np.stack((arr1, arr2, arr3))
print(arr_stacked)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#stack horizontally
arr_hstacked = np.hstack((arr1, arr2, arr3))
print(arr_hstacked)


[1 2 3 4 5 6 7 8 9]


**Views v/s Copies**
When you create a view of an array, you are essentially creating a new array object that references the same memory location as the original array. This means that any changes made to the view will also affect the original array, since they both reference the same data.

In [4]:
arr = np.array([1, 2, 3, 4, 5])

# Create a view of the array
arr_view = arr[1:]

# Print the original array and the view
print("Original array:", arr)
print("View:", arr_view)

# Modify the view
arr_view[0] = 10

# Print the original array and the view
print("Original array:", arr)
print("View:", arr_view)


Original array: [1 2 3 4 5]
View: [2 3 4 5]
Original array: [ 1 10  3  4  5]
View: [10  3  4  5]


On the other hand, when you create a copy of an array, you are creating a new array object that contains a copy of the data from the original array. This means that any changes made to the copy will not affect the original array, since they are separate arrays with separate data.

It is important to note that creating a view of an array is generally faster and uses less memory than creating a copy of an array, since it does not need to allocate new memory for the data. However, creating a view of an array can also be more dangerous, since any changes made to the view will also affect the original array.

In [5]:
# Create a 1-dimensional array with 5 elements
arr = np.array([1, 2, 3, 4, 5])

# Create a copy of the array
arr_copy = arr.copy()

# Print the original array and the copy
print("Original array:", arr)
print("Copy:", arr_copy)

# Modify the copy
arr_copy[0] = 10

# Print the original array and the copy
print("Original array:", arr)
print("Copy:", arr_copy)

Original array: [1 2 3 4 5]
Copy: [1 2 3 4 5]
Original array: [1 2 3 4 5]
Copy: [10  2  3  4  5]


**Math and linear algebra**

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.add(A, B)
print(C)

[[ 6  8]
 [10 12]]


In [7]:
D = np.subtract(A, B)
print(D)

[[-4 -4]
 [-4 -4]]


In [8]:
E = np.dot(A, B)
print(E)

[[19 22]
 [43 50]]


In [9]:
#dot plot is the same as matmul

E = np.matmul(A, B)
print(E)

[[19 22]
 [43 50]]


In [10]:
# element-wise

E = A*B
print(E)

[[ 5 12]
 [21 32]]


In [11]:
# element-wise

F = np.divide(A, B)
print(F)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [12]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
