<a href="https://colab.research.google.com/github/szh141/colab/blob/main/matrix_multiplication_and_convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
a2 = np.arange(9)
print(np.dot(a2,a2)) #dot product on vector

204


In [5]:
a1 = np.arange(9).reshape(3,3)
print(a1)
print(a1*a1) #element-wise multiplication
print(np.dot(a1,a1)) #dot product on matrix is the same as below, @ or np.matmul
print(a1@a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [ ]:
"""
matrix multiplication of higher dimension
(510,510,3,4) @ (510,510,4,3) is the 510x510 times multiplications of 3x4 matrix with 4x3 matrix
the result is (510,510,3,3) since multiplication of 3x4 matrix with 4x3 matrix yields 3x3
"""

In [ ]:
"""
e.g. sobel_h 3x3 kernel convolution on an image, is windowed_img (510,510,3,3).reshape(510,510,1,9) @ kernl (510,510,3x3).reshape(510,510,9,1)
this yields (510,510,1,1), not displayable in matplotlib. Therefore, add the pixel value into 510x510 canvas

array2 = np.repeat(kernel[np.newaxis,:,:], repeats=510, axis=0)
array3 = np.repeat(array2[np.newaxis,:,:,:], repeats=510, axis=0)
array3_2 =array3.reshape(510,510,9,1)

here array3_2 is the repeated array of 3x3 sobel_h kernel into 510x510x3x3

a5 = windowed_img_2@array3_2
a6 = np.zeros((510,510))
for i in range(510):
  for j in range(510):
    a6[i,j] = a5[i,j]

plt.imshow(a6>0.07)
"""